non_blocking_read needs to get EAGAIN from the errno module
this commit fixes the following traceback

  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/runner.py", line 32, in execute_assert_success
    return self.execute(*args, **kwargs)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/runner.py", line 27, in execute
    returned.wait()
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/result.py", line 108, in wait
    returned_results = wait_for_many_results([self], timeout=timeout)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/waiting.py", line 18, in wait_for_many_results
    _sweep_finished_results(results, ioloop)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/waiting.py", line 50, in _sweep_finished_results
    if result.is_finished():
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/result.py", line 115, in is_finished
    return self.poll() is not None
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/result.py", line 97, in poll
    self._check_return_code()
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/result.py", line 103, in _check_return_code
    flush(self)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/waiting.py", line 27, in flush
    ioloop.flush()
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/ioloop.py", line 103, in flush
    [self._handle_readable(r) for r in self._reads.keys()]
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/ioloop.py", line 114, in _handle_readable
    handler(self, f, count=count)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/result.py", line 87, in _handle_stderr
    output = non_blocking_read(self._popen.stderr, count)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/utils.py", line 72, in non_blocking_read
    return retry_loop_on_eagain(file_obj.read, count)
  File "/private/var/root/python/lib/python2.7/site-packages/infi.execute-0.1-py2.7.egg/infi/execute/utils.py", line 60, in retry_loop_on_eagain
    return func(*args, **kwargs)
IOError: [Errno 35] Resource temporarily unavailable